spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test8?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    drive-class-name: com.mysql.jdbc.Driver
